language: node_js
node_js:
- 10.14.1
branches:
  only:
  - develop

install: npm install

before_script:
- git config --global user.name "Victor Jordan"
- git config --global user.email "victorjordan95@gmail.com"
- npm install -g gulp
- gulp build
- cd ./build
script: npm run build